# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.TextField()),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('type', models.TextField()),
                ('vendor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.TextField()),
                ('date', models.DateTimeField()),
                ('moduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.Module')),
            ],
        ),
    ]
