# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.TextField()),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('type', models.TextField()),
                ('vendor', models.TextField()),
            ],
        ),
    ]
