# Generated by Django 2.0 on 2018-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='authCode',
            field=models.TextField(default='authCodeHashHere'),
            preserve_default=False,
        ),
    ]
