# Generated by Django 2.0.7 on 2018-08-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
