# Generated by Django 2.0 on 2018-12-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_module_authcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='api.User'),
        ),
    ]
