# Generated by Django 2.0.7 on 2018-08-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ownerUserId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='athomeBoxes', to='api.User')),
            ],
        ),
    ]
