# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180427_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
