# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180427_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.TextField()),
                ('date', models.DateTimeField()),
                ('samples', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduleId', to='api.Module')),
            ],
        ),
    ]
