# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='samples',
            new_name='moduleId',
        ),
    ]
