# Generated by Django 2.0.7 on 2018-08-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180825_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='authCode',
            field=models.TextField(default='authCodeHashHere'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='ownerUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boxes', to='api.User'),
        ),
    ]
