# Generated by Django 2.0.7 on 2018-08-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180826_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='api.Box'),
        ),
    ]
