# Generated by Django 2.0.7 on 2018-08-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_module_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='ownerUserId',
        ),
    ]
