# Generated by Django 2.0.7 on 2018-08-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_box_owneruserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='ownerUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boxes', to='api.User'),
        ),
    ]
