# Generated by Django 2.0.7 on 2018-08-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_box_owneruserid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='ownerUserId',
            new_name='user',
        ),
    ]
