# Generated by Django 2.0.7 on 2018-08-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180828_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='boxes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Box'),
        ),
    ]
