# Generated by Django 2.0.7 on 2018-08-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180828_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boxes',
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boxes', to='api.User'),
        ),
    ]
