# Generated by Django 2.0 on 2018-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180828_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.TextField(default='defaultSalt;42<{}>'),
        ),
    ]
