# Generated by Django 2.0 on 2018-09-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
