# Generated by Django 2.0 on 2018-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180912_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.TextField(default=''),
        ),
    ]
